### ISSUE TITLE
error in line 20 Bubble sort

### ISSUE THREAD

**Issue by divaibhav** [dbc2201/SortingRepo#1]
[link for error](https://github.com/dbc2201/SortingRepo/blob/d83b3e907f65a440daa7c8ae38b319cb7b019f75/src/bubblesort/BubbleSort.java#L20)

can be resolved by changing it to `if (array[j] > array[j + 1]) {`

**Comment by dbc2201** [comment]
Code is for descending order sort, sir.  
I'll refactor the logic into two methods.

**Comment by dbc2201** [comment]
Fixed!
